[package]
name = "leetcode-rust"
version = "1.0.0"
authors = ["pom"]
edition = "2024"

[dependencies]
# Current versions can be found at https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages
itertools = "0.14"
rand = "0.8"
regex = "1"

cargo-leet = "0.3.0"
rstest = "0.26.1"
